### 음식 이미지 업로드 presigned-url 생성 API
POST localhost:8080/api/v1/meals/images/presigned-url
Content-Type: application/json

{
  "contentType": "image/jpeg",
  "fileSizeBytes": 1000
}

### 발급받은 presigned url로 이미지 S3에 업로드
PUT https://nyummy-app-bucket-455615001241-ap-northeast-2-an.s3.ap-northeast-2.amazonaws.com/temp/179d17b0-8c80-4346-a7ff-9a7f7580e26f.jpg?x-id=PutObject&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAWUFGFGKM4PNRWFHW%2F20260806%2Fap-northeast-2%2Fs3%2Faws4_request&X-Amz-Date=20260806T075403Z&X-Amz-Expires=600&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Signature=b1b9eb534dc5e3d435b52fd9bf8e4f1885546b7c209725031ba06d9a1808d4ad
Content-Type: image/jpeg

< image/crazy_spicy.jpeg


### 식사기록 생성 API
POST localhost:8080/api/v1/meals
Content-Type: application/json

{
  "name": "bad case 3 / solution 1",
  "imageKey": "temp/179d17b0-8c80-4346-a7ff-9a7f7580e26f.jpg",
  "mealAt": "2026-08-05T07:12:26Z",
  "iconId": 1
}

### 분석 상태 조회 API
@mealId = 10
GET localhost:8080/api/v1/meals/{{mealId}}/analysis

### 재분석 요청 API
POST localhost:8080/api/v1/meals/{{mealId}}/analysis