### 음식 이미지 업로드 presigned-url 생성 API
POST {{url}}/api/v1/meals/images/presigned-url
Content-Type: application/json

{
  "contentType": "image/png",
  "fileSizeBytes": 1000
}

### 식사기록 생성 API
POST {{url}}/api/v1/meals
Content-Type: application/json

{
  "name": "눈알짱구",
  "imageKey": "temp/ede107bb-d176-469e-aa2d-8b834fa792b8.png",
  "mealAt": "2026-07-20T07:12:26Z",
  "iconId": 1
}

### 분석 상태 조회 API
@mealId = 1
GET {{url}}/api/v1/meals/{{mealId}}/analysis

### 재분석 요청 API
POST {{url}}/api/v1/meals/{{mealId}}/analysis